version: '3.8'

services:
  app:
    build:
      dockerfile: ./Dockerfile
    volumes:
    - .:/usr/src/KOMTEK
    depends_on:
      - postgres
    ports:
    - 80:8000
    environment:
      POSTGRES_USER: KOMTEK
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: KOMTEK
      DATABASE: POSTGRES

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: KOMTEK
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: KOMTEK
    volumes:
    - ./.data/postgres:/var/lib/postgresql/data

