# Generated by Django 3.2.4 on 2021-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='catalog',
            name='unique_version',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='catalog',
        ),
        migrations.AddField(
            model_name='catalog',
            name='identifier',
            field=models.CharField(default=None, max_length=50, verbose_name='идентификатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='items',
            field=models.ManyToManyField(to='api.CatalogItem'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='identifier',
            field=models.CharField(default='', max_length=50, verbose_name='идентификатор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='parent_identifier',
            field=models.CharField(default='1', max_length=50, verbose_name=' родительский идентификатор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='наименование'),
        ),
        migrations.AddConstraint(
            model_name='catalog',
            constraint=models.UniqueConstraint(fields=('identifier', 'version'), name='unique_version'),
        ),
    ]
