# Generated by Django 3.2.4 on 2021-06-25 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210623_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'get_latest_by': 'date', 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочники'},
        ),
        migrations.AlterModelOptions(
            name='catalogitem',
            options={'verbose_name': 'Элемент справочника', 'verbose_name_plural': 'Элементы справочников'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='items',
            field=models.ManyToManyField(blank=True, to='api.CatalogItem'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='parent_identifier',
            field=models.CharField(max_length=50, verbose_name='родительский идентификатор'),
        ),
    ]
